# Generated by Django 3.1.3 on 2020-11-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='fileName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
